method: grid

parameters:
  seed:
    values:
      - 0
      - 1
      - 2

command:
  - ${env}
  - python
  - -m
  - llm_rl_scripts.maze.bc.fully_observed_bc
  - HF
  - gpt2
  - datasets/fully_observed_maze_data.jsonl
  - --outputs-path=bc_train_maze_checkpoints
  - --epochs=100
  - --train_bsize=128
  - --eval_frac=0.9
  - --save_every_epochs=10
  - --save_at_end
  - --use_wandb
  - --wandb_project=bc_maze
  - ${args}
