method: grid

parameters:
  seed:
    values: [1, 2, 3]
  cql_weight:
    values:
      - 1
  beta:
    values: [16, 32, 24]
  tau:
    values: [0.9, 0.95]

command:
  - ${env}
  - python3
  - -m
  - llm_rl_scripts.maze.iql.train_iql
  - PARAMS
  - bc_train_maze_checkpoints/2202
  - datasets/fully_observed_maze_data.jsonl
  - --outputs-path=iql_train_maze_checkpoints/test/1epoch_search/
  - --epochs=1
  - --train_bsize=64
  - --eval_every_epochs=2
  - ${args}
